NEO4J_URI = "URI"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "password"
UMLS_API_KEY = "UMLS_API_KEY"
GPT_API_KEY = "GPT_API_KEY"
BERT_1 = "dmis-lab/biobert-v1.1"
BERT_2 = "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract"